#!/usr/bin/env bash
# Refresh the bundled field-knowledge vaults.
#
# Pulls the latest from the two Thrive knowledge vault repos and re-bakes their
# vault/ directories into this skill's references/vaults/ folder, so the skill
# carries current field context wherever it runs (Claude Code, Claude Desktop,
# the uploaded zip) without needing network access at research time.
#
# Read-only with respect to the source repos: it clones and fetches, never pushes.
# Both repos are public, so no auth is required.
#
# Usage:  ./scripts/refresh-vaults.sh
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST_ROOT="$SKILL_DIR/references/vaults"
CACHE_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}/thrive-field-vaults"

# name|repo slug — the directory name under references/vaults/ and its source repo.
VAULTS=(
  "k12|thrive-incubator/k12-synthesis"
  "headstart|thrive-incubator/headstart-synthesis"
)

for tool in git rsync; do
  command -v "$tool" >/dev/null 2>&1 || { echo "error: $tool is required but not installed." >&2; exit 1; }
done

mkdir -p "$CACHE_ROOT" "$DEST_ROOT"

SNAPSHOT="$DEST_ROOT/SNAPSHOT.md"
{
  echo "# Vault snapshot"
  echo
  echo "Generated by \`scripts/refresh-vaults.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "Re-run that script to bring this up to date. Digests land weekly, so a snapshot"
  echo "more than ~7 days old is likely missing a week."
  echo
} > "$SNAPSHOT"

for entry in "${VAULTS[@]}"; do
  name="${entry%%|*}"
  repo="${entry##*|}"
  cache="$CACHE_ROOT/$name"
  dest="$DEST_ROOT/$name"

  echo "==> $name  ($repo)"

  if [ -d "$cache/.git" ]; then
    git -C "$cache" fetch --quiet --depth 1 origin HEAD
    git -C "$cache" reset --quiet --hard FETCH_HEAD
  else
    rm -rf "$cache"
    git clone --quiet --depth 1 "https://github.com/$repo.git" "$cache"
  fi

  if [ ! -d "$cache/vault" ]; then
    echo "error: $repo has no vault/ directory — the upstream layout may have changed." >&2
    exit 1
  fi

  mkdir -p "$dest"
  rsync -a --delete \
    --exclude '.obsidian/' \
    --exclude '_template.md' \
    "$cache/vault/" "$dest/"

  sha="$(git -C "$cache" rev-parse --short HEAD)"
  committed="$(git -C "$cache" log -1 --format=%cs)"
  latest_digest="$(find "$dest/digests" -name '*.md' 2>/dev/null | sort | tail -1 | xargs -I{} basename {} .md)"
  file_count="$(find "$dest" -name '*.md' | wc -l | tr -d ' ')"

  {
    echo "## $name"
    echo
    echo "- Source: \`$repo\` (public), \`vault/\`"
    echo "- Commit: \`$sha\`, committed $committed"
    echo "- Latest digest: **${latest_digest:-none}**"
    echo "- Files: $file_count markdown pages"
    echo
  } >> "$SNAPSHOT"

  echo "    $file_count pages · latest digest ${latest_digest:-none} · $sha ($committed)"
done

echo
echo "Baked into: $DEST_ROOT"
echo "Snapshot:   $SNAPSHOT"
